version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper


  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker


  postgres:
    image: postgres:latest
    container_name: postgres
     

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es-container


  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana